#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6463464743                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get your things done like a Blitz!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.


# Information About Yourself
your_name                                 : Sascha Krug                             
your_link                                 : https://blitzgtd.fa-krug.de                     
your_city                                 : Munich                                
email_address                             : support@fa-krug.de
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : SaschaKrug
youtube_username                          :
mastodon_link                             : 


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Like a Blitz!
    description                           : Discover the definitive implementation of BlitzGTD with our app, serving as the ideal embodiment of its capabilities. Explore more details <a href="/blitzgtd">here</a>.
    fontawesome_icon_name                 : bolt-lightning

  - title                                 : Tags
    description                           : Elevate your organization game by effortlessly categorizing your items with vibrant and visually appealing tags.
    fontawesome_icon_name                 : tag

  - title                                 : Quick actions
    description                           : Our app is optimized for swift task completion through various means like hotkeys, gestures, menus, widgets, shortcuts, deep-links, and terminal integration.
    fontawesome_icon_name                 : truck-fast
    
  - title                                 : Global search
    description                           : Effortlessly search across all lists with a simple swipe or a quick hotkey, granting you instant access to the information you need.
    fontawesome_icon_name                 : magnifying-glass

  - title                                 : Scheduler
    description                           : Schedule your items for the future with ease, whether it's a one-time event or a recurring task, using the convenient CronTab integration.
    fontawesome_icon_name                 : clock

  - title                                 : Daily and weekly planner
    description                           : Revamp the structure of your lists effortlessly using the daily and weekly planner feature. Gain control over your organization and seamlessly reorganize your tasks to maximize productivity.
    fontawesome_icon_name                 : book-open-reader

  - title                                 : Apple Reminders
    description                           : Easily import your Reminders into BlitzGTD and consolidate your tasks. Seamlessly transfer your existing reminders for a unified and streamlined task management experience.
    fontawesome_icon_name                 : down-long
    
  - title                                 : Markdown
    description                           : Capture all the essential details about an item in its details section using Markdown formatting. Seamlessly incorporate text formatting, lists, links, tables, and more to provide comprehensive and rich information within the item's details.
    fontawesome_icon_name                 : markdown

# Theme Settings
topbar_color                              : "#53B29C"
topbar_transparency                       : 0.5
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#53B29C"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#53B29C"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
